version: "3.8"

services:
  maria:
    image: mariadb:11.1
    restart: always
    container_name: maria
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/vol:/var/lib/mysql
    ports:
      - 9050:3306
    healthcheck:
      test: mariadb -u ${MARIADB_USER} -p${MARIADB_PASSWORD} -h maria
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s

  predictor:
    build:
      context: ./predictor
      dockerfile: Dockerfile
    restart: always
    container_name: predictor
    environment:
      DEPOFLOWDB_USER: ${DEPOFLOWDB_USER}
      DEPOFLOWDB_PASSWORD: ${DEPOFLOWDB_PASSWORD}
      DEPOFLOWDB_NAME: ${DEPOFLOWDB_NAME}
    ports:
      - 9040:8080
    depends_on:
      maria:
        condition: service_healthy

  scrapper:
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    container_name: scrapper
    ports:
      - 9041:8080
    depends_on:
      predictor:
        condition: service_started

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 9080:5173
    depends_on:
      predictor:
        condition: service_started
